version: "3.7"
services:
  web:
    command: npm run dev
    container_name: vending-docker-development
    environment:
      - FE_API=http://127.0.0.1:8000/api/
    volumes:
      - ./:/vending
      - /vending/node_modules
      - /vending/.next
      